"""Shared canonicalization for Ghana constituency names (project crosswalk)."""
import re, unicodedata

def norm(s):
    s = str(s).upper().strip()
    s = unicodedata.normalize('NFKD', s)
    s = re.sub(r"[\/\-\.\,\(\)\']", ' ', s)
    return re.sub(r'\s+', ' ', s).strip()

XW = {
 'AMENFI EAST':'WASSA AMENFI EAST','ASHIAMAN':'ASHAIMAN','CHIREPONI':'CHEREPONI','GUSHIEGU':'GUSHEGU','GUSHEIGU':'GUSHEGU','GUSHEIEGU':'GUSHEGU',
 'BIBIANI ANWIASO BEKWAI':'BIBIANI ANHWIASO BEKWAI','SEFWI AKONTONBRA':'SEFWI AKONTOMBRA','SEWFI AKONTOMBRA':'SEFWI AKONTOMBRA',
 'BOTIANOR NGLESHIE':'BORTIANOR NGLESHIE AMANFRO','AKUAPIM NORTH':'AKWAPIM NORTH','AKUAPEM NORTH':'AKWAPIM NORTH','AKROPONG':'AKWAPIM NORTH',
 'AKUAPIM SOUTH':'AKWAPIM SOUTH','AKUAPEM SOUTH':'AKWAPIM SOUTH','TWIFO ATI MORKWAA':'TWIFO ATTI MORKWA','TWIFO ATII MORKWAA':'TWIFO ATTI MORKWA','TWIFO ATTI MORKWAA':'TWIFO ATTI MORKWA',
 'NADAWLI KALEO':'NADOWLI KALEO','ZEBILLA':'BAWKU WEST','LAMBUSSIE KARNE':'LAMBUSSIE','LAMBUSSIE KARNI':'LAMBUSSIE','LUMBUSSIE':'LAMBUSSIE',
 'EFFIDUASI ASOKORE':'EFFIDUASE ASOKORE','EFUTU':'EFFUTU',
 'KOMENDA EDINA EGUAFO ABIREM':'KOMENDA EDINA EGUAFO ABREM KEEA','KOMENDA EDINA EGUAFO ABREM':'KOMENDA EDINA EGUAFO ABREM KEEA','KEEA':'KOMENDA EDINA EGUAFO ABREM KEEA','KOMENA EDINA EGUAFO ABIREM':'KOMENDA EDINA EGUAFO ABREM KEEA','EGUAFO ABIREM':'KOMENDA EDINA EGUAFO ABREM KEEA',
 'ANYAA SOWOTUOM':'ANYAA SOWUTUOM','ABURA A KWAMANKESE':'ABURA ASEBU KWAMANKESE','ABURA ASEBU KWAMAKESE':'ABURA ASEBU KWAMANKESE','KWAMANKESE':'ABURA ASEBU KWAMANKESE',
 'ADENTA':'ADENTAN','AJUMAKO ENYAM ESIAM':'AJUMAKO ENYAN ESIAM','AJUMAKO ENYAN ESSIAM':'AJUMAKO ENYAN ESIAM','ASOUGYAMAN':'ASUOGYAMAN',
 'ATEBUBU AMANTIM':'ATEBUBU AMANTIN','ATEBUBU AMANTING':'ATEBUBU AMANTIN','AYAWASO WEST WOUGON':'AYAWASO WEST WUOGON','AYAWASO WEST':'AYAWASO WEST WUOGON',
 'BIMBILA':'BIMBILLA','DADE KOTOPON':'DADEKOTOPON','DADEKOTOPONG':'DADEKOTOPON','ELLEMBELLE':'ELLEMBELE','ESIKADU KETAN':'ESSIKADU KETAN','ESSIKADO KETAN':'ESSIKADU KETAN',
 'MFANTSIMAN EAST':'MFANTSEMAN EAST','NEW ADUBIASE':'NEW EDUBIASE','NEW EDUBEASE':'NEW EDUBIASE','NKAWKAAW':'NKAWKAW','NKWAKWA':'NKAWKAW',
 'ODODODIODOO':'ODODODIODIOO','ODODODIODIO':'ODODODIODIOO','OFORIKOM':'OFORIKROM',
 'KASSENA NANKANA EAST':'NAVRONGO CENTRAL','KASSENA NANKANA WEST':'CHIANA PAGA',
 'WASA AMENFI EAST':'WASSA AMENFI EAST','WASA AMENFI WEST':'WASSA AMENFI WEST','AMENFI WEST':'WASSA AMENFI WEST',
 'EVALUE AJOMORO GWIRA':'EVALUE GWIRA','AVALUE GWIRA':'EVALUE GWIRA','TATALE SANGULI':'TATALE SANGULE',
 'KWESIMINTIM':'KWESIMINTSIM','NALERIGU GAMBAGA':'NALERIGU','NALERIGU GAMGABA':'NALERIGU','AOWIM SUAMAN':'AOWIN SUAMAN','BINDEPENDENTURI':'BINDURI',
 'PRESTEA HUNIVALLEY':'PRESTEA HUNI VALLEY','SWALA KALBA':'SAWLA TUNA KALBA','SAWLA KALBA':'SAWLA TUNA KALBA','SALWA TUNA KALBA':'SAWLA TUNA KALBA',
 'BAWKU CETRAL':'BAWKU CENTRAL','DAMANGO':'DAMONGO','KPONE K':'KPONE KATAMANSO','KPONE KATAMANSU':'KPONE KATAMANSO',
 'ADANSI AKROFUOM':'AKROFUOM','AKROFROM':'AKROFUOM','ADANSI ASOKWA NORTH':'ADANSI ASOKWA','DORMA WEST':'DORMAA WEST','BOLE BAMBOI':'BOLE',
 'SEKYERE AFRAM PLAIN':'SEKYERE AFRAM PLAINS','NABDEM':'NABDAM','TWIFU HEMANG LOWER DENKYIRA':'TWIFO HEMAN LOWER DENKYIRA','TWIFU HEMANG LOWER DANKYIRA':'TWIFO HEMAN LOWER DENKYIRA',
 'AFFIA KWESIMINTIN':'EFFIA KWESIMINTIM','EFFIA KWESIMINTSIM':'EFFIA KWESIMINTIM','BUNKPURUGU YUNYOO':'BUNKPURUGU','JUABESO':'JUABOSO','AVENOR':'AVENOR AVE','LOWER MANYA':'LOWER MANYA KROBO','UPPER MANYA':'UPPER MANYA KROBO',
}

def canon(s):
    n = norm(s)
    n = XW.get(n, n)
    n = re.sub(r'\bAHAFO AND\b', 'AHAFO ANO', n)
    n = re.sub(r'\bATWIWA\b', 'ATWIMA', n)
    n = re.sub(r'\bASIKUMA OD\w+ BRAKWA\b|\bASIKUMA OBOBEN BRAKWA\b', 'ASIKUMA ODOBEN BRAKWA', n)
    # The three towns are written in either order on different sources
    # (EC sheets say "Asene Manso Akroso"); fix on the panel's dominant form.
    n = re.sub(r'\bASENE MANSO AKROSO\b', 'ASENE AKROSO MANSO', n)
    return XW.get(n, n)
